/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndktest_GetString */

#ifndef _Included_com_example_ndktest_GetString
#define _Included_com_example_ndktest_GetString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndktest_GetString
 * Method:    getstr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndktest_GetString_getstr
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ndktest_GetString
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndktest_GetString_getStr
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndktest_GetString
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndktest_GetString_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_ndktest_GetString
 * Method:    getWords
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndktest_GetString_getWords
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
