/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndktest_GetInt */

#ifndef _Included_com_example_ndktest_GetInt
#define _Included_com_example_ndktest_GetInt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndktest_GetInt
 * Method:    getint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_ndktest_GetInt_getint
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
